

$MACRO Ten_Bit_Counter Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9

Q0.d  =
    !Q0;

Q1.d  =
    !Q0 & Q1
  # Q0 & !Q1;

Q2.d  =
    !Q0 & Q1 & Q2
  # Q0 & Q1 & !Q2
  # !Q1 & Q2;

Q3.d  =
    !Q0 & Q1 & Q2 & Q3
  # Q0 & Q1 & Q2 & !Q3
  # !Q1 & Q2 & Q3
  # !Q2 & Q3;

Q4.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4
  # Q0 & Q1 & Q2 & Q3 & !Q4
  # Q1 & Q2 & !Q3 & Q4
  # !Q2 & Q4
  # !Q1 & Q2 & Q4;

Q5.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5
  # Q0 & Q1 & Q2 & Q3 & Q4 & !Q5
  # Q1 & Q2 & Q3 & !Q4 & Q5
  # !Q3 & Q5
  # Q1 & !Q2 & Q3 & Q5
  # !Q1 & Q3 & Q5;

Q6.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & !Q6
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q6
  # !Q2 & Q3 & Q6
  # !Q3 & Q6
  # Q1 & Q2 & Q3 & !Q4 & Q6
  # !Q1 & Q2 & Q3 & Q6;

Q7.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q7
  # !Q2 & Q4 & Q7
  # !Q3 & !Q4 & Q7
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q7
  # Q2 & !Q3 & Q4 & Q7
  # !Q2 & Q3 & !Q4 & Q7
  # !Q1 & Q2 & Q3 & Q7
  # Q1 & Q2 & Q3 & !Q4 & Q7;

Q8.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & !Q8
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7 & Q8
  # !Q1 & Q3 & Q4 & Q8
  # !Q3 & !Q4 & !Q5 & Q8
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q8
  # Q2 & !Q3 & !Q4 & Q5 & Q8
  # !Q2 & Q3 & !Q4 & !Q5 & Q8
  # !Q2 & !Q4 & Q5 & Q8
  # Q2 & Q3 & !Q4 & Q8
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q8
  # !Q3 & Q4 & Q8
  # Q1 & !Q2 & Q3 & Q4 & Q8;

Q9.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & Q9
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & !Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & !Q8 & Q9
  # !Q1 & Q2 & Q3 & Q4 & Q9
  # !Q3 & !Q4 & !Q5 & !Q6 & Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7 & Q9
  # Q2 & !Q3 & !Q4 & !Q5 & Q6 & Q9
  # !Q2 & Q3 & !Q4 & !Q5 & !Q6 & Q9
  # !Q2 & !Q4 & !Q5 & Q6 & Q9
  # Q2 & Q3 & !Q4 & !Q5 & Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q9
  # !Q3 & Q4 & !Q5 & Q9
  # Q3 & !Q4 & Q5 & Q9
  # !Q3 & Q5 & Q9
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q9
  # !Q2 & Q3 & Q4 & Q9;

$MEND


$MACRO Eleven_Bit_Counter Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10

Q0.d  =
    !Q0;

Q1.d  =
    !Q0 & Q1
  # Q0 & !Q1;

Q2.d  =
    !Q0 & Q1 & Q2
  # Q0 & Q1 & !Q2
  # !Q1 & Q2;

Q3.d  =
    !Q0 & Q1 & Q2 & Q3
  # Q0 & Q1 & Q2 & !Q3
  # !Q1 & Q2 & Q3
  # !Q2 & Q3;

Q4.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4
  # Q0 & Q1 & Q2 & Q3 & !Q4
  # Q1 & Q2 & !Q3 & Q4
  # !Q2 & Q4
  # !Q1 & Q2 & Q4;

Q5.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5
  # Q0 & Q1 & Q2 & Q3 & Q4 & !Q5
  # Q1 & Q2 & Q3 & !Q4 & Q5
  # !Q3 & Q5
  # Q1 & !Q2 & Q3 & Q5
  # !Q1 & Q3 & Q5;

Q6.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & !Q6
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q6
  # !Q2 & Q3 & Q6
  # !Q3 & Q6
  # Q1 & Q2 & Q3 & !Q4 & Q6
  # !Q1 & Q2 & Q3 & Q6;

Q7.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q7
  # !Q2 & Q4 & Q7
  # !Q3 & !Q4 & Q7
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q7
  # Q2 & !Q3 & Q4 & Q7
  # !Q2 & Q3 & !Q4 & Q7
  # !Q1 & Q2 & Q3 & Q7
  # Q1 & Q2 & Q3 & !Q4 & Q7;

Q8.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & !Q8
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7 & Q8
  # !Q1 & Q3 & Q4 & Q8
  # !Q3 & !Q4 & !Q5 & Q8
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q8
  # Q2 & !Q3 & !Q4 & Q5 & Q8
  # !Q2 & Q3 & !Q4 & !Q5 & Q8
  # !Q2 & !Q4 & Q5 & Q8
  # Q2 & Q3 & !Q4 & Q8
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q8
  # !Q3 & Q4 & Q8
  # Q1 & !Q2 & Q3 & Q4 & Q8;

Q9.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & Q9
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & !Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & !Q8 & Q9
  # !Q1 & Q2 & Q3 & Q4 & Q9
  # !Q3 & !Q4 & !Q5 & !Q6 & Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7 & Q9
  # Q2 & !Q3 & !Q4 & !Q5 & Q6 & Q9
  # !Q2 & Q3 & !Q4 & !Q5 & !Q6 & Q9
  # !Q2 & !Q4 & !Q5 & Q6 & Q9
  # Q2 & Q3 & !Q4 & !Q5 & Q9
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q9
  # !Q3 & Q4 & !Q5 & Q9
  # Q3 & !Q4 & Q5 & Q9
  # !Q3 & Q5 & Q9
  # Q1 & Q2 & Q3 & Q4 & !Q5 & Q9
  # !Q2 & Q3 & Q4 & Q9;

Q10.d  =
    !Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & Q9 & Q10
  # Q0 & Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & Q9 & !Q10
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & Q8 & !Q9 & Q10
  # !Q2 & Q5 & Q10
  # !Q3 & !Q4 & !Q5 & !Q6 & !Q7 & Q10
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & Q7 & !Q8 & Q10
  # Q2 & !Q3 & !Q4 & !Q5 & !Q6 & Q7 & Q10
  # !Q2 & Q3 & !Q4 & !Q5 & !Q6 & !Q7 & Q10
  # !Q2 & !Q4 & !Q5 & !Q6 & Q7 & Q10
  # Q2 & Q3 & !Q4 & !Q5 & !Q6 & Q10
  # Q1 & Q2 & Q3 & Q4 & Q5 & Q6 & !Q7 & Q10
  # !Q3 & Q4 & !Q5 & !Q6 & Q10
  # Q3 & !Q4 & !Q5 & Q6 & Q10
  # !Q3 & !Q5 & Q6 & Q10
  # Q1 & Q2 & Q3 & Q4 & Q5 & !Q6 & Q10
  # Q3 & Q4 & !Q5 & Q10
  # Q1 & Q2 & Q3 & !Q4 & Q5 & Q10
  # Q1 & Q2 & !Q3 & Q5 & Q10
  # !Q1 & Q2 & Q5 & Q10;

$MEND



